import datetime
import random
import time


PERCENTAGECPU_DATA = {
        'ADVA FSP3000R7': {
            'parentelement': '62e71893-92e0-11e9-b465-d4856454f4ba',
            'webid': 'F1AbEfLbwwL8F6EiShvDV-QH70AkxjnYuCS6RG0ZdSFZFT0ugnMRtEzvxdFojNpadLPwI4gWE9NUEFTUy1MSVRTTFxMSVRTQU5MRUFORFJPXDc3NyBEQVZJU1xQT1AgUk9PTVxBRFZBIEZTUDMwMDBSN3xQSU5H',
        },
        'Ubiquiti OLT': {
            'parentelement': 'd515dccb-58be-11ea-b46d-d4856454f4ba',
            'webid': 'F1AbEfLbwwL8F6EiShvDV-QH70Ay9wV1b5Y6hG0bdSFZFT0ugxACfpGU7d1ojPpadLPwI4gWE9NUEFTUy1MSVRTTFxMSVRTQU5MRUFORFJPXDc3NyBEQVZJU1xQT1AgUk9PTVxVQklRVUlUSSBPTFR8UElORw',
        },
        'VM Lit SL NMS': {
            'parentelement': '1ab3b14e-93b1-11e9-b465-d4856454f4ba',
            'webid': 'F1AbEfLbwwL8F6EiShvDV-QH70ATrGzGrGT6RG0ZdSFZFT0ugQW05a2rwdFojNpadLPwI4gWE9NUEFTUy1MSVRTTFxMSVRTQU5MRUFORFJPXDc3NyBEQVZJU1xQT1AgUk9PTVxGLk8gTU9OSVRPUklORyBTRVJWRVJcVk0gTElUIFNMIE5NU3xQSU5H',
        },
        'Catalyst 3500XL': {
            'parentelement': '68ae8bef-92e1-11e9-b465-d4856454f4ba',
            'webid': 'F1AbEfLbwwL8F6EiShvDV-QH70A74uuaOGS6RG0ZdSFZFT0ug4FckGTrxdFojNpadLPwI4gWE9NUEFTUy1MSVRTTFxMSVRTQU5MRUFORFJPXDc3NyBEQVZJU1xQT1AgUk9PTVxDQVRBTFlTVCAzNTAwWEx8UElORw',
        },
        'GOOGLE_PING': {
            'parentelement': 'f0bd0832-a81e-11ea-b46d-d4856454f4ba',
            'webid': 'F1AbEfLbwwL8F6EiShvDV-QH70AMgi98B6o6hG0bdSFZFT0ugPdQ3gcXLd1ojPpadLPwI4gWE9NUEFTUy1MSVRTTFxMSVRTQU5MRUFORFJPXDc3NyBEQVZJU1xHT09HTEVfUElOR3xQSU5H',
        },
}


def get_percentagecpu_data(sleep:float, repeat:int)->list:
    """
    Generate the percentage of CPU used per device
    :args:
        sleep:float - wait time between each row
        repeat:int - number of times to repeat process
    :param:
        data_set:list - list of data sets
    :sample:
      {
         "device_name": "Catalyst 3500XL",
         "parentelement": "68ae8bef-92e1-11e9-b465-d4856454f4ba",
         "timestamp": "2020-12-08 02:20:11.024002",
         "value": 15.2,
         "webid": "F1AbEfLbwwL8F6EiShvDV-QH70A74uuaOGS6RG0ZdSFZFT0ug4FckGTrxdFojNpadLPwI4gWE9NUEFTUy1MSVRTTFxMSVRTQU5MRUFORFJPXDc3NyBEQVZJU1xQT1AgUk9PTVxDQVRBTFlTVCAzNTAwWEx8UElORw"
      }
    :return:
      data dict based on information generated by PERCENTAGECPU_DATA
    """
    data_sets = []

    for i in range(repeat):
        device_name = random.choice(list(PERCENTAGECPU_DATA.keys()))
        data_sets.append(
            {
                'timestamp': datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S.%fZ'),
                'device_name': device_name,
                'parentelement': PERCENTAGECPU_DATA[device_name]['parentelement'] ,
                'webid': PERCENTAGECPU_DATA[device_name]['webid'] ,
                'value': round(random.random() * 100, 2)
            }
        )
        time.sleep(sleep)

    return data_sets


if __name__ == '__main__':
    print(get_percentagecpu_data(sleep=1, repeat=10))