[metadata]
name = Data-Generator
version = 1.0 (data-generator2 - e376aa [2026-03-23 21:55:01])
author = AnyLog Co.
contact = info@anylog.co
description = AnyLog REST CLI Tool
license = Copyright AnyLog Co.
site = https://anylog.co
;docs=
source = https://github.com/AnyLog-co/Remote-CLI

;[options]
;packages = find:s
