[metadata]
name = Data-Generator
version = 1.0 (pre-develop - db6c83 [2026-05-12 00:13:41])
author = AnyLog Co.
contact = info@anylog.co
description = AnyLog REST CLI Tool
license = Copyright AnyLog Co.
site = https://anylog.co
;docs=
source = https://github.com/AnyLog-co/Remote-CLI

;[options]
;packages = find:s
