[metadata]
name = Data-Generator
version = 1.0 (data-generator2 - 2ba69e [2026-03-19 23:04:25])
author = AnyLog Co.
contact = info@anylog.co
description = AnyLog REST CLI Tool
license = Copyright AnyLog Co.
site = https://anylog.co
;docs=
source = https://github.com/AnyLog-co/Remote-CLI

;[options]
;packages = find:s
